stages:
  - build
  - test
  - deploy
  
image: gradle:latest

gradle_build:
  stage: build
  script:
    - gradle build

gradle_test:
  stage: test
  script:
    - gradle test
    
gradle_deploy:
  stage: deploy
  script:
    - echo "$signing_key" > "$key_name"
    - echo "$release_flag" >> local.properties
    - echo "$sonatype_user_flag""$sonatype_user" >> local.properties
    - echo "$sonatype_pass_flag""$sonatype_pass" >> local.properties
    - echo "$signing_key_flag""$key_id" >> local.properties
    - echo "$signing_key_pass_flag""$signing_pass" >> local.properties
    - echo "$signing_key_name_flag""$key_name" >> local.properties
    - gradle clean
    - gradle uploadArchives
    - rm "$key_name"
    - rm local.properties
