stages:
  - build
  - deploy
  
image: archiver

gradle_build:
  stage: build
  script:
    - gradle build
    - gradle test
    
gradle_deploy:
  stage: deploy
  script:
    - echo "" >> gradle.properties
    - echo "$release_flag" >> gradle.properties
    - cp ~/local.properties .
    - gradle clean
    - gradle uploadArchives
    - rm ~/secring.gpg
    - rm local.properties
