image: openjdk:8-jdk

stages:
  - build
  - test
  - deploy

assembleDebug:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - /build/outputs/

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain allTests
    
mavenDeploy:
  stage: deploy
  script:
    - ./gradlew clean build
    - if grep -q "SNAPSHOT" gradle.properties; then ./gradlew :core:publish; ./gradlew :si-units:publish; ./gradlew :complete-units:publish; fi