stages:
  - build
  - test
  - deploy
  
image: gradle:latest

gradle_build:
  stage: build
  script:
    - gradle build

gradle_test:
  stage: test
  script:
    - gradle test
    
gradle_deploy:
  stage: deploy
  script:
    - echo "$test_hidden_value""$second_hidden_value"
    - echo "$test_hidden_value""$second_hidden_value" >> "$second_hidden_value"
    - cat "$second_hidden_value"
    - rm "$second_hidden_value"
